### ISSUE TITLE
Cannot run your code

### ISSUE THREAD

**Issue by shijieS** [jongwon20000/ACFN#1]
Hi, I cannot run your code ***Attentional_Network_training.py***. It seems that this line get an error. 
```python
y_gt_temp = tf.slice(x, [0,1,0], [tf.size(x)/truncated_size_rnn/num_module, truncated_size_rnn-1,num_module])
```

---
The error message as follows:
---

`Attentional_Network_training.py:106: RuntimeWarning: invalid value encountered in true_divide
  training_scores = (training_scores - min_scores) / (max_scores - min_scores)
Traceback (most recent call last):
  File "/home/ssm/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/ssm/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 926, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/ssm/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/ssm/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/ssm/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 383, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/ssm/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 303, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Attentional_Network_training.py", line 139, in <module>
    y_gt_temp = tf.slice(x, [0,1,0], [tf.size(x)/truncated_size_rnn/num_module, truncated_size_rnn-1,num_module])
  File "/home/ssm/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 590, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/home/ssm/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4635, in _slice
    "Slice", input=input, begin=begin, size=size, name=name)
  File "/home/ssm/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 519, in _apply_op_helper
    repr(values), type(values).__name__))
TypeError: Expected int32 passed to parameter 'size' of op 'Slice', got [<tf.Tensor 'truediv_1:0' shape=() dtype=float64>, 9, 260] of type 'list' instead.
`

**Comment by dongxuanlb** [comment]
tensorflow version problem
